[package]
name = "depcheck_cli"
version = "0.1.0"
authors = ["awesome author"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.0.10", features = ["cargo", "derive"]}
